Prefix: '&7[&6Mi Tier&7] &f'

defaultIfNotSet: 1.0 # Nếu stat chưa có trên item thì sẽ dùng giá trị này để tính toán
StatsUp: # Chỉ số Stats sẽ tăng trong khoảng khi giám định
  EPIC: # Tier id
    SWORD: # Loại vũ khí
      attack-damage:
        type: PERCENT # Loại tăng (PERCENT hoặc NUMBER)
        min: 1.0 # Tăng tối thiểu (Tương đương 1%)
        max: 2.5 # Tăng tối đa (Tương đương 2.5%)
    AXE:
      attack-damage:
        type: PERCENT
        min: 1.0
        max: 2.5
  COMMON:
    SWORD:
      max-durability:
        type: NUMBER
        min: 1
        max: 1000